-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.teams
(
    id bigserial NOT NULL,
    name character varying(255) NOT NULL,
    coach character varying(255) NOT NULL,
    city character varying(255) NOT NULL,
    stadium character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tournaments
(
    id bigserial NOT NULL,
    name character varying(255) NOT NULL,
    start_date date,
    end_date date,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.players
(
    id bigserial NOT NULL,
    team_id bigint NOT NULL,
    firstname character varying(255) NOT NULL,
    lastname character varying(255) NOT NULL,
    birth_date date NOT NULL,
    player_position character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.applications
(
    id bigserial NOT NULL,
    tournament_id bigint NOT NULL,
    team_id bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.matches
(
    id bigserial NOT NULL,
    tournament_id bigint NOT NULL,
    team1_id bigint NOT NULL,
    team2_id bigint NOT NULL,
    date date NOT NULL,
    stadium character varying(255) NOT NULL,
    scored_goals_team1 integer NOT NULL DEFAULT 0,
    scored_goals_team2 integer NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.effective_actions
(
    id bigserial NOT NULL,
    match_id bigint NOT NULL,
    player_id bigint NOT NULL,
    type character varying(255) NOT NULL,
    minute match_minute NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.players_applications
(
    player_id bigint NOT NULL,
    application_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.action_types
(
    type character varying(255) NOT NULL,
    PRIMARY KEY (type)
);

CREATE TABLE IF NOT EXISTS public.player_positions
(
    player_position character varying(255) NOT NULL,
    PRIMARY KEY (player_position)
);

CREATE TABLE IF NOT EXISTS public.cities
(
    city character varying(255) NOT NULL,
    PRIMARY KEY (city)
);

CREATE TABLE IF NOT EXISTS public.stadiums
(
    stadium character varying(255) NOT NULL,
    PRIMARY KEY (stadium)
);

ALTER TABLE IF EXISTS public.teams
    ADD FOREIGN KEY (city)
    REFERENCES public.cities (city) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.teams
    ADD FOREIGN KEY (stadium)
    REFERENCES public.stadiums (stadium) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.players
    ADD FOREIGN KEY (team_id)
    REFERENCES public.teams (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.players
    ADD FOREIGN KEY (player_position)
    REFERENCES public.player_positions (player_position) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.applications
    ADD FOREIGN KEY (team_id)
    REFERENCES public.teams (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.applications
    ADD FOREIGN KEY (tournament_id)
    REFERENCES public.tournaments (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.matches
    ADD FOREIGN KEY (tournament_id)
    REFERENCES public.tournaments (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.matches
    ADD FOREIGN KEY (team1_id)
    REFERENCES public.teams (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.matches
    ADD FOREIGN KEY (team2_id)
    REFERENCES public.teams (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.matches
    ADD FOREIGN KEY (stadium)
    REFERENCES public.stadiums (stadium) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.effective_actions
    ADD FOREIGN KEY (match_id)
    REFERENCES public.matches (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.effective_actions
    ADD FOREIGN KEY (player_id)
    REFERENCES public.players (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.effective_actions
    ADD FOREIGN KEY (type)
    REFERENCES public.action_types (type) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.players_applications
    ADD FOREIGN KEY (player_id)
    REFERENCES public.players (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.players_applications
    ADD FOREIGN KEY (application_id)
    REFERENCES public.applications (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;